# Auto-upgraded manifest for Odoo 18 scaffolding
{'name': 'Orchid Account Enhancement',
 'version': '18.1',
 'summary': 'OrchidERP Accounting',
 'author': 'OrchidERP',
 'website': 'http://www.orchiderp.com',
 'license': 'LGPL-3',
 'depends': ['account','account_reports' ],
 'data': [
     # 'wizard/overdue_wizard_view.xml',
          # 'wizard/od_overdue.xml',
          # 'wizard/account_report_partner_ledger_view.xml',
          # 'wizard/account_report_aged_partner_balance_view.xml',
          # 'wizard/account_report_general_ledger_view.xml',
          'security/ir.model.access.csv',
          # 'views/account_view.xml',
          # 'views/account_division.xml',
          # 'views/account_branch.xml',
          'views/account_cost_center.xml',
          # 'views/account_invoice_view.xml',
          # 'report/report_template.xml',
          # 'report/payment_print.xml',
          # 'report/receivable_payable_print.xml',
          # 'report/account_payment_analysis_view.xml',
          # 'report/overdue_partner_print_view.xml',
          # 'report/report_financial.xml',
          # 'report/report_orchid__partner_statement.xml',
          # 'report/report_orchid_invoice_aging.xml',
          # 'wizard/payment_collection_rpt_view.xml',
          # 'wizard/duplicate_entry_view.xml',
          # 'wizard/account_financial_report_view.xml',
          # 'wizard/invoice_wise_aging_view.xml',
          # 'report/payment_collection_print_view.xml',
          # 'views/account_move_view.xml'
          ],
 'demo': [],
 'qweb': []}