# Auto-upgraded manifest for Odoo 18 scaffolding
{'name': 'Orchid Sports',
 'version': '18.1',
 'summary': 'Orchid Sports',
 'author': 'OrchidERP',
 'website': ['http://www.orchiderp.com'],
 'license': 'LGPL-3',
 'depends': ['base',
             'analytic',
             'account_reports',
             'account',
             'orchid_account_enhancement',
             'orchid_vat_v10'],
 'data': ['security/ir.model.access.csv',
          'wizard/collection_history_detail_wizard_view.xml',
          'wizard/od_new_collection_reportwizard_view.xml',
          'wizard/view_partner_collection.xml',
          'wizard/od_vat_inv_seq_wiz_view.xml',
          'wizard/tax_register_wiz.xml',
          'views/od_sports_receipt_seq_view.xml',
          'views/od_sports_attenadance_seq_view.xml',
          'views/od_activity_seq_view.xml',
          'views/od_venue_view.xml',

          'views/od_esports_menu.xml',

          'views/od_activities_view.xml',
          'views/od_sports_receipt_view.xml',
          'views/od_refund_entry_view.xml',
          'views/od_lesson_transfer_view.xml',
          'views/od_sports_date_selection_view.xml',
          'views/od_sports_attenadance_seq_view.xml',
          'views/od_sports_attenadance_view.xml',
          'views/od_registration_from_program_view.xml',
          'views/od_scheduled_view.xml',
          'views/od_camp_type_view.xml',
          'views/od_pdc_release.xml',
          'views/res_partner_view.xml',
          'views/orchid_parameter.xml',
          'report/od_sports_attenadance_analysis_view.xml',
          'report/od_sports_receipt_analysis_view.xml',
          'report/od_activity_analysis_view.xml',
          'report/report_view.xml',
          'report/report_template.xml',
          'report/report_partner_collection.xml',
          'report/od_sports_receipt_line_print.xml',
          'report/collection_print.xml',
          'report/vat_invoice_print.xml',
          'report/od_lesson_transfer_analysis_view.xml',
          'views/student_master_view.xml',
          'views/od_terms_view.xml',

          'wizard/booking_sheet_report_wizard_view.xml',


          'report/booking_sheet_report_new_view.xml',
          # 'report/payment_print_inherit.xml', fix it todo
          'views/account_view.xml',
          # 'report/account_invoice_analysis_report_view.xml'
          ],
 'demo': [],
 'qweb': []}
